module.exports = {
  "articleArray":
      {
        "data":
            {
              "message": {
                "status": "success",
                "code": "code",
                "text": "successfully fetched data"
              },
              "payload":{
                "data":[
                  {
                    "id":1,
                    "author":"Author1",
                    "title":"Title1",
                    "dateAdded":"2022-02-02",
                    "images":[
                      {
                        "portrait":[
                          "https://picsum.photos/900/1600",
                          "https://picsum.photos/450/800"
                        ],
                        "landscape":[
                          "https://picsum.photos/1600/900",
                          "https://picsum.photos/800/450"
                        ]
                      }
                    ],
                    "likes":10
                  },
                  {
                    "id":2,
                    "author":"Author2",
                    "title":"Title2",
                    "dateAdded":"2020-10-10",
                    "images":[
                      {
                        "portrait":[
                          "https://picsum.photos/900/1600",
                          "https://picsum.photos/450/800"
                        ],
                        "landscape":[
                          "https://picsum.photos/1600/900",
                          "https://picsum.photos/800/450"
                        ]
                      }
                    ],
                    "likes":20
                  },
                  {
                    "id":3,
                    "author":"Author3",
                    "title":"Title3",
                    "dateAdded":"2021-05-05",
                    "images":[
                      {
                        "portrait":[
                          "https://picsum.photos/900/1600",
                          "https://picsum.photos/450/800"
                        ],
                        "landscape":[
                          "https://picsum.photos/1600/900",
                          "https://picsum.photos/800/450"
                        ]
                      }
                    ],
                    "likes":30
                  }
                ]
              }
            }
      },
  "article":
      {
        "id":1,
        "author":"Author1",
        "title":"Title1",
        "dateAdded":"2022-01-20",
        "images":[
          {
            "portrait":[
              "https://picsum.photos/900/1600",
              "https://picsum.photos/450/800"
            ],
            "landscape":[
              "https://picsum.photos/1600/900",
              "https://picsum.photos/800/450"
            ]
          }
        ],
        "likes":10
      }
}

